<a href="https://colab.research.google.com/github/Yashika007-J/Data-analyst-intern/blob/main/Pandas_Assignment_Day_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <center>Pandas Assignment</center>

Import pandas and numpy with their aliases

In [3]:

import pandas as pd
import numpy as np

Create a variable a = pd.Series([ 100, 200, 300, 400])

In [26]:
a = pd.Series([100,200,300,400])

Print a, and data type

In [27]:
print(a)
print(a.dtype)

0    100
1    200
2    300
3    400
dtype: int64
int64

Using indexing access the element 300 from the series a.

In [6]:
(a[2])

np.int64(300)

What are the values of index for series a?

In [7]:
(a.index)

RangeIndex(start=0, stop=4, step=1)

Change the index to  ['c', 'a', 'b', 'd']

In [44]:
a=pd.Series([100,200,300,400],index=['c', 'a', 'b', 'd'])
print(a)

c    100
a    200
b    300
d    400
dtype: int64

Access the value in the series with index 'd'

In [45]:
print(a['d'])

400

Sort the values wrt to the index and print it

In [46]:
print(a.sort_index())

a    200
b    300
c    100
d    400
dtype: int64

Create a new Pandas Series b having index as 'e', 'f', and 'g' and value 800,450,100 and print it

In [40]:
b = pd.Series([800,450, 100],index=['e', 'f', 'g'])
print(b)

e    800
f    450
g    100
dtype: int64

Append b series at the end of a series

In [47]:
a = pd.concat([a, b])
print(a)

c    100
a    200
b    300
d    400
e    800
f    450
g    100
dtype: int64

In [48]:
#print a again after appending b into it
a

c    100
a    200
b    300
d    400
e    800
f    450
g    100
dtype: int64

Sort the values in descending order of a and print the index of the sorted series

In [51]:
a = a.sort_values(ascending=False)
print((a).index)

Index(['e', 'f', 'd', 'b', 'a', 'c', 'g'], dtype='object')

## Pandas DataFrame

### Part 1

Create a pandas dataframe df from the series 'a' that we used in the last section, print the dataframe

In [98]:
df = pd.DataFrame(a)
print(df)

     0
e  800
f  450
d  400
b  300
a  200
c  100
g  100

What is the shape of the datafarme <br>
(also, what does it imply?)

In [99]:
df.shape

(7, 1)

Hey! remember shape (7,1) implies dataframe has 7 rows and 1 column.

What is the index of the dataframe, is it same as the series 'a'

In [59]:
# yep its same as the series.

print the head and tail of the dataframe. <br>
Additional - (what does head and tali represent?)

In [100]:
df.head()

     0
e  800
f  450
d  400
b  300
a  200

In [101]:
df.tail()

     0
d  400
b  300
a  200
c  100
g  100

Rename the column of the dataframe as 'points'

In [102]:
df.columns = ['points']
print(df)

   points
e     800
f     450
d     400
b     300
a     200
c     100
g     100

Create another Series 'fruits', which contains random names of fruits from ['orange','mango','apple']. The series should contain 7 elements, randomly selected from ['orange','mango','apple']

In [103]:
#Create fruits array

fruits = pd.Series(np.random.choice(['orange', 'mango', 'apple'], 7))
print(fruits)

0     mango
1     apple
2     apple
3     apple
4     apple
5    orange
6    orange
dtype: object

Change the index of fruits to the index of dataframe df

In [104]:
fruits.index = df.index
print(fruits)

e     mango
f     apple
d     apple
b     apple
a     apple
c    orange
g    orange
dtype: object

Add this fruits series as a new column to the dataframe df with its column name as 'fruits'
<br>print the head of the dataframe to verify

In [107]:
df['fruits']=fruits
print(df.head())

   points fruits
e     800  mango
f     450  apple
d     400  apple
b     300  apple
a     200  apple

## Pandas Concatenation

Create a dataframe  d1 where the cols are  ‘city’ : [‘Chandigarh’, ‘Delhi’, ‘Kanpur’, ‘Chennai’, ‘Manali’ ] and ‘Temperature’ : [15, 22, 20, 26,-2]

In [111]:
d1 = pd.DataFrame({'city' :['Chandigarh', 'Delhi', 'Kanpur', 'Chennai', 'Manali' ],
                   'Temperature':[15, 22, 20, 26,-2]})
print(d1)

         city  Temperature
0  Chandigarh           15
1       Delhi           22
2      Kanpur           20
3     Chennai           26
4      Manali           -2

Print(d1)

In [113]:
d1

         city  Temperature
0  Chandigarh           15
1       Delhi           22
2      Kanpur           20
3     Chennai           26
4      Manali           -2

What is the shape of d1.

In [114]:
d1.shape

(5, 2)

Set city = d1['city']

In [115]:

city =d1['city']

print city <br>
What is the type of city.

In [117]:
city
print(city.dtype)

object

Create another datafeame 'd2' where the columns are <br>
'city' - ['Bengalaru','Coimbatore','Srirangam','Pondicherry'] <br>
'Temperature' - [24,35,36,39]

In [123]:
d2 =pd.DataFrame({'city':['Bengalaru','Coimbatore','Srirangam','Pondicherry'],
                          'Temperature' : [24,35,36,39]})
print(d2)

          city  Temperature
0    Bengalaru           24
1   Coimbatore           35
2    Srirangam           36
3  Pondicherry           39

print the shape of this dataframe

In [122]:
d2.shape

(4, 2)

merge the two dataframes together, save it in a new dataframe named 'd3'

In [138]:
d3 = pd.concat([d1,d2])
print(d3)

          city  Temperature
0   Chandigarh           15
1        Delhi           22
2       Kanpur           20
3      Chennai           26
4       Manali           -2
0    Bengalaru           24
1   Coimbatore           35
2    Srirangam           36
3  Pondicherry           39

Select the part of the dataframe such that it contains cities wherer temp is less then or equal to 20 <br>
How many cities are there?

In [137]:
temp = d3[d3['Temperature'] <= 20]
print(temp)
print(len(temp))

         city  Temperature
0  Chandigarh           15
2      Kanpur           20
4      Manali           -2
3

Select the part of the dataframe such that it contains the cities where tempearature greater than or equal to 35

In [139]:
cities = d3[d3['Temperature'] >= 35]
print(cities)

          city  Temperature
1   Coimbatore           35
2    Srirangam           36
3  Pondicherry           39

## Applying functions to columns and creating new columns

We need to create another column in d3, which contains  a boolean value for each city to indicate whether it's a union territory or not.
- HINT: Chandigarh, Pondicherry and Delhi are only 3 union territories here.

In [140]:
# write function here

# def is_ut(x):

#     # write code below

# d3['is_ut'] =
def is_ut(x):
    return x in ['Chandigarh', 'Pondicherry', 'Delhi']

d3['is_ut'] = d3['city'].apply(is_ut)
print(d3)

          city  Temperature  is_ut
0   Chandigarh           15   True
1        Delhi           22   True
2       Kanpur           20  False
3      Chennai           26  False
4       Manali           -2  False
0    Bengalaru           24  False
1   Coimbatore           35  False
2    Srirangam           36  False
3  Pondicherry           39   True

In [141]:
# print d3
d3

          city  Temperature  is_ut
0   Chandigarh           15   True
1        Delhi           22   True
2       Kanpur           20  False
3      Chennai           26  False
4       Manali           -2  False
0    Bengalaru           24  False
1   Coimbatore           35  False
2    Srirangam           36  False
3  Pondicherry           39   True

The temperatures mentioned in ‘Temperature’ column are mentioned in Celsius, we need another column which contains the same in Fahrenheit.

HINT -
- Define a function c_to_f which takes input temp in celsius and returns a value with temperature in Fahrenheit.
- To check: c_to_f(10) should return 50.

In [151]:
# write function here
def c_to_f(temp):
    return (temp * 9/5) + 32

print(c_to_f(10))

50.0

In [147]:
# check function c_to_f(10)
c_to_f(10)

50.0

In [153]:
# apply function c_to_f to d3 to create a column 'temp_farenhiet'
d3['temp_farenhiet'] = c_to_f(d3['Temperature'])
print(d3)

          city  Temperature  is_ut  temp_farenhiet
0   Chandigarh           15   True            59.0
1        Delhi           22   True            71.6
2       Kanpur           20  False            68.0
3      Chennai           26  False            78.8
4       Manali           -2  False            28.4
0    Bengalaru           24  False            75.2
1   Coimbatore           35  False            95.0
2    Srirangam           36  False            96.8
3  Pondicherry           39   True           102.2

## Indexing and selecting rows in DataFrame

Select subset of the dataframe d1 such that it contains the cities which are union territories.

In [154]:
d1 = d3[d3['is_ut']]
print(d1)

          city  Temperature  is_ut  temp_farenhiet
0   Chandigarh           15   True            59.0
1        Delhi           22   True            71.6
3  Pondicherry           39   True           102.2

Select a subset of the dataframe d1 such that it contains the cities which only have temperature above 90 Farenhiet.

In [156]:
d1 = d3[d3['temp_farenhiet'] > 90]
print(d1)

          city  Temperature  is_ut  temp_farenhiet
1   Coimbatore           35  False            95.0
2    Srirangam           36  False            96.8
3  Pondicherry           39   True           102.2

Select only the first three rows of the dataframe d1.

In [160]:
d1 = d3.head(3)
print(d1)

         city  Temperature  is_ut  temp_farenhiet
0  Chandigarh           15   True            59.0
1       Delhi           22   True            71.6
2      Kanpur           20  False            68.0
   is_ut  temp_farenhiet
0   True            59.0
1   True            71.6
2  False            68.0

Select all the rows and last two columns in the dataframe.

In [161]:
d1 = d3.tail(2)
print(d1)
print(d1.iloc[:, -2:])

          city  Temperature  is_ut  temp_farenhiet
2    Srirangam           36  False            96.8
3  Pondicherry           39   True           102.2
   is_ut  temp_farenhiet
2  False            96.8
3   True           102.2

## Groupby

In [167]:
# Create a dataframe using dictionary of your choice

data ={'Name':['Yashika','khushi','yash'],
       'Age':[21,20,22],
       'city':['Uttarakhand','mumbai','UP']}
df=pd.DataFrame(data)
print(df)

      Name  Age         city
0  Yashika   21  Uttarakhand
1   khushi   20       mumbai
2     yash   22           UP

In [170]:
# Use Groupby of single column with aggregate sum()
gp = df.groupby('Name').sum()
print(gp)

         Age         city
Name
Yashika   21  Uttarakhand
khushi    20       mumbai
yash      22           UP

In [169]:
# Use Groupby of single column with aggregate count()
gp = df.groupby('Name').count()
print(gp)

         Age  city
Name
Yashika    1     1
khushi     1     1
yash       1     1

In [174]:
# Use Groupby of single column with aggregate min() and max()
print(df.groupby('Name').min())
print(df.groupby('Name').max())

         Age         city
Name
Yashika   21  Uttarakhand
khushi    20       mumbai
yash      22           UP
         Age         city
Name
Yashika   21  Uttarakhand
khushi    20       mumbai
yash      22           UP

In [181]:
# Use Groupby of any 2 columns with aggregate mean()
print(df.groupby(['city', 'Name']).mean())

                      Age
city        Name
UP          yash     22.0
Uttarakhand Yashika  21.0
mumbai      khushi   20.0

In [183]:
# Use Groupby of any 2 columns with aggregate min() and max()
print(df.groupby(['city', 'Name']).min())
print(df.groupby(['city', 'Name']).max())

                     Age
city        Name
UP          yash      22
Uttarakhand Yashika   21
mumbai      khushi    20
                     Age
city        Name
UP          yash      22
Uttarakhand Yashika   21
mumbai      khushi    20

## Data Range

Create a pandas daterange where starting date is 1st of January,2020 and end date is 1st of April 2021, store it in a new variable named 'a'

In [184]:
a = pd.date_range(start='2020-01-01', end='2021-04-01')
print(a)

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
               '2020-01-09', '2020-01-10',
               ...
               '2021-03-23', '2021-03-24', '2021-03-25', '2021-03-26',
               '2021-03-27', '2021-03-28', '2021-03-29', '2021-03-30',
               '2021-03-31', '2021-04-01'],
              dtype='datetime64[ns]', length=457, freq='D')

print a

In [185]:
a

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
               '2020-01-09', '2020-01-10',
               ...
               '2021-03-23', '2021-03-24', '2021-03-25', '2021-03-26',
               '2021-03-27', '2021-03-28', '2021-03-29', '2021-03-30',
               '2021-03-31', '2021-04-01'],
              dtype='datetime64[ns]', length=457, freq='D')

What is the len of a?

In [186]:
print(len(a))

457

What is the type of a?

In [191]:
print(a.dtype)

datetime64[ns]